# Zadanie 02 (a)

---

#### Dokonaj dekompozycji LU metodą Doolittle'a, macierzy 

$$\mathbf{A} = \left[\begin{array}{rrrrr} 9 & 8 &-2 & 2 &-2 \\  7 &-3 &-2 & 7 & 2 \\ 2 &-2 & 2 &-7 & 6 \\ 4 & 8 &-3 & 3 &-1 \\ 2 & 2 &-1 & 1 & 4 \end{array}\right]$$

#### a następnie korzystając z macierzy $\mathbf{L}$ oraz $\mathbf{U}$ rozwiąż poniższy układ równań 

$$\mathbf{A} \cdot x = \left[\begin{array}{rrrrr} 9 & 8 &-2 & 2 &-2 \\  7 &-3 &-2 & 7 & 2 \\ 2 &-2 & 2 &-7 & 6 \\ 4 & 8 &-3 & 3 &-1 \\ 2 & 2 &-1 & 1 & 4 \end{array}\right] \cdot \left[\begin{array}{c} x_{1} \\ x_{2} \\ x_{3} \\ x_{4} \\ x_{5} \end{array}\right] = \left[\begin{array}{r} 21 \\ 11 \\ -4 \\ 16 \\ 9 \end{array}\right]$$

**Punktacja**
+ funkcja implementacja metodę Doolittle **3p.**
+ rozwiązanie układu równańc **1p.** (przy pomocy macierzy $\mathbf{L}$ i $\mathbf{U}$)

## Teoria
---
### Dekomozycja LU

W metodzie LU macierz współczynników $\mathbf {A}$ zapisywana jest jako iloczyn dwóch macierzy trójkątnych, macierzy trójkątnej dolnej $\mathbf {L}$ i macierzy trójkątnej górnej $\mathbf {U}$:

$$\mathbf{A} = \mathbf{L} \cdot \mathbf{U}$$ gdzie 

$\mathbf{L} =
\begin{bmatrix}
1      & 0      & \cdots & 0 \\
l_{21} & 1      & \cdots & 0 \\
\vdots & \vdots & \ddots & 0 \\
l_{n1} & l_{n2} & \cdots & 1
\end{bmatrix}$ oraz $\mathbf{U} = 
\begin{bmatrix}u_{11} & u_{12} & \cdots & u_{1n} \\
0      & u_{22} & \cdots & u_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
0      & 0      & \cdots & u_{nn}
\end{bmatrix}$

###  Metoda Doolittle

Metody Doolittle'a przedstawia wzory pozwalające na obliczenie poszczególnych wartości macierzy rozkładu, i tak elementy macierzy $\mathbf{U}$ dane są wzorem
$$u_{ij} = a_{ij} - \sum_{k=1}^{i-1} l_{ik} u_{kj}$$ dla $j\in\{i,\ i+1,\ \ldots,\ n\}$

a elementy macierzy $\mathbf{L}$ 
$$l_{ji} = \frac{1}{u_{ii}} \left(a_{ji} - \sum_{k=1}^{i-1} l_{jk} u_{ki} \right)$$ dla $j\in\{i+1,\ i+2,\ \ldots,\ n\}$

### Rozwiązanie układu równań przy pomocy macierzy $\mathbf {L}$ i $\mathbf {U}$

Mając macierz trójkątną dolną oraz górną w łatwy sposób (oszczędny numerycznie) można rozwiązać układ równań liniowych, wystarczy zauważyć, że

$$\mathbf {L} \cdot \mathbf {U} \cdot \mathbf {x} =\mathbf {y}$$

stąd rozwiązanie otrzyamy przez rozwiązanie dwóch układów z macierzami trójkątnymi

$$\mathbf{L} \cdot \mathbf{z} = \mathbf{y}$$
$$\mathbf{U} \cdot \mathbf{x} = \mathbf{z}$$


## Wykonanie
---
Wczytanie bibliotek

In [1]:
import numpy as np
from scipy.linalg import solve_triangular

Przypisanie wartości dla macierzy A

In [2]:
A = np.array([[9, 8,-2, 2,-2],[7,-3,-2, 7, 2],[2,-2,2,-7,6],[4, 8,-3, 3,-1],[2, 2,-1, 1, 4]])
print(A)

[[ 9  8 -2  2 -2]
 [ 7 -3 -2  7  2]
 [ 2 -2  2 -7  6]
 [ 4  8 -3  3 -1]
 [ 2  2 -1  1  4]]


Implementacja metody Doolittle

In [133]:
def doolittle(M):
    L = np.identity(M.shape[0])
    U = np.zeros(M.shape)
    
    for i in range(M.shape[0]):
        for j in range(i+1):
            
            r = 0
            for k in range(j):
                r+=L[j,k]*U[k,i]
                
            U[j,i]=A[j,i]-r
        
        for j in range(i+1,M.shape[0]):
            
            r = 0
            for k in range(j):
                r+=L[j,k]*U[k,i]
      
            L[j,i]=1/U[i,i]*(A[j,i]-r)
        
    return L, U

Obliczenie macierzy $\mathbf{L}$ oraz $\mathbf{U}$ dla macierzy $\mathbf{A}$

In [135]:
L, U = doolittle(A)
U

array([[ 9.        ,  8.        , -2.        ,  2.        , -2.        ],
       [ 0.        , -9.22222222, -0.44444444,  5.44444444,  3.55555556],
       [ 0.        ,  0.        ,  2.62650602, -9.6746988 ,  4.98795181],
       [ 0.        ,  0.        ,  0.        , -3.83027523,  6.01834862],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  3.40718563]])

Sprawdzenie poprawności wyniki. Jeżeli funkcja zwróci wartość `True` to iloczyn macierzy  $\mathbf{L}$ i  $\mathbf{U}$ jest równy macierzy $\mathbf{A}$.

In [136]:
print(np.allclose(L @ U, A))

True


Rozwiązanie układu równań

In [146]:
y = np.array([21,11,-4,16,9])

z = solve_triangular(L, y, lower=True)
x = solve_triangular(U, z, lower=False)
print(x)

[ 1.  2.  3.  2.  1.]


In [147]:
print(np.allclose(A @ x, y))

True
